Rebuild for protobuf 3.12.3
Build currently fail because of 
```
$PREFIX/include/gazebo-11/gazebo/msgs/cessna.pb.h:56:51: error: no type named 'AuxillaryParseTableField' in namespace 'google::protobuf::internal'; did you mean 'AuxiliaryParseTableField'?
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
```
Which was renamed in protobuf 3.12.3. Last build had protobuf 3.12.1